chore: fix CI pipeline
charmed-hpc/slurmd-operator pull request #38
Opened 2024-07-15 23:09 UTC by jedel1043

This will always pull from `main` when testing against `slurmctld-operator`, which is arguably better when trying to do breaking changes in integrations between the charms.

## How was the code tested?

Locally using a development environment based on Ubuntu Jammy.

## Checklist

- [x] I am the author of these changes, or I have the rights to submit them.
- [x] I have added the relevant changes to the README and/or documentation.
- [x] I have self reviewed my own code.
- [ ] All requested changes and/or review comments have been resolved.

2024-07-16 23:08 UTC, NucciTheBoss requested changes
I agree with dropping `slurmdbd` from the tests since we now only need `slurmctld` and `slurmd` to reach active state for both charms. I just have two comments. Comment number 1 I'd like to have addressed in this PR, and comment 2 is :taco::four::thinking: that we should discuss in the future: 

1. I think we should still be testing against the edge branch of the slurmctld operator in Charmhub as a non-gating test. Reason saying is that we should at least have some insight into whether the latest changes to the slurmd operator are compatible with the latest published version of slurmctld. That way we have a flag for whether we're intentionally or unintentionally breaking the API between the two charms. If we're intentionally breaking, we can comment the context on the PR, and if we're unintentionally breaking, we know that we have some further debugging to do. Let me know your thoughts on this.

2. We should have discussion about what smoke testing will look like for Charmed HPC. I definitely think that a full-scale Charmed HPC cluster will quickly overwhelm a single GitHub Runner, so we should brainstorm what those tests will eventually look like, and where to run them.

2024-07-16 23:27 UTC, jedel1043 commented
> 1. I think we should still be testing against the edge branch of the slurmctld operator in Charmhub as a non-gating test. Reason saying is that we should at least have some insight into whether the latest changes to the slurmd operator are compatible with the latest published version of slurmctld. That way we have a flag for whether we're intentionally or unintentionally breaking the API between the two charms. If we're intentionally breaking, we can comment the context on the PR, and if we're unintentionally breaking, we know that we have some further debugging to do. Let me know your thoughts on this.

I think that would be good, that way we do breaking changes in a more controlled way.

2024-07-16 23:37 UTC, NucciTheBoss commented
> I think that would be good, that way we do breaking changes in a more controlled way.

Sweet! Let's do that then, we can have the integration test against the edge branch in Charmhub run concurrently with the main integration test against the cloned version of slurmctld.

2024-07-17 16:01 UTC, jamesbeedy approved these changes
Sweet! +1

2024-07-17 18:24 UTC, jedel1043 commented
@NucciTheBoss Added a non-gating step that tests against Charmhub edge, PTAL.

2024-07-17 18:43 UTC, NucciTheBoss approved these changes
LGTM :rocket: 

Have the insight into whether we're breaking with what's published in edge will be very nice to have!

2024-07-17 18:43 UTC, merged